### ISSUE TITLE
確認：マッパー登録はインポートアカウントで登録？

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/task-bldg#10]
インポートを行う際には、インポート用のアカウントを使用することになっています。
現在のこのサイトではマッパー登録はログインしているユーザー名で自動登録されるようですので、
作業者にインポートアカウントで作業することを認識してもらうためにも、このサイトもインポート作業の作業者登録にはインポートアカウントでしてもらった方が良いんでしょうね。

とすると、現在は検証者とマッパーが同一の場合はシステム側で検証登録できないようにしていますが、インポートアカウントと通常アカウントでそれぞれマッパー/検証者を登録すれば同一人物でもできてしまうのですかね。。
（そこは運用で「同一人物がやらないでね」と言えば良いですが）

**Comment by yuuhayashi** [comment]
作業をインポートアカウントで行った場合は実際に作業を行ったマッパーが誰なのかわからなくなるため、ログインに登録してもらうのはリマッパーが識別できるほうのOSMアカウント名で登録してほしいと思っています。
開発者のスキル的な問題で"task-bldg"のユーザ登録プロセスに脆弱性（ユーザ認証をしていない）がありますので、不正行為を行おうとするユーザに対してはなんの対策もできていません。この辺は利用者の善意にすがるだけとしています。
