### ISSUE TITLE
改善提案：都市ごとのリストについて

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/task-bldg#5]
良さそうな感じですね。ありがとうございます。

都市ごとのファイル一覧のページ(*1)での改善提案です。
(*1:例：http://surveyor.mydns.jp/task-bldg/mesh/01100のようなページ)
・マッパーと検証者をリストの項目に追加すると、誰がやる予定なのかがパッと見でわかって良いかなと思います。
・ステータスや地域メッシュ、（上の追加がOKなら、マッパーと検証者も）で、リストの昇順・降順の並べ替えがボタンでできるとより良いかなと思います。(Excelやwikiのソート付きリストのようなイメージ)

**Comment by yuuhayashi** [comment]
提案ありがとうございます。
実現する方法を考えてみます。

**Comment by yuuhayashi** [comment]
Issue #8 
と 
Issue #9
に分割しました。
