### ISSUE TITLE
改善提案: 進捗状況のアイコン

### ISSUE THREAD

**Issue by nyampire** [yuuhayashi/task-bldg#6]
Hと色合いだけだと分かりづらいので、「作業予約中」「編集完了」のように文字表示のほうが良いのではないでしょうか。

もし色合いで示す場合は、どこかに凡例があると嬉しいです。

**Comment by yuuhayashi** [comment]
[サイトの使い方](https://github.com/yuuhayashi/task-bldg/wiki#%E3%83%9D%E3%83%BC%E3%82%BF%E3%83%AB%E3%82%B5%E3%82%A4%E3%83%88%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9) に、状態遷移図にステート色を表示しました。
