### ISSUE TITLE
改善提案: 「事前チェック」段階の追加

### ISSUE THREAD

**Issue by nyampire** [yuuhayashi/task-bldg#7]
現在の作業計画では、インポート前に「事前チェック」の工程を設けようとしています。（必須作業にするかどうかは要検討）

例えば、明らかに間違いの建物の有無（地元知識や航空写真でのチェック）や、既存の道路データとの整合性のチェックを行います。

![スクリーンショット 2022-08-10 17 27 15](https://user-images.githubusercontent.com/428218/183853456-c0bf0a4b-9a41-4e37-96e8-608065ff9805.png)

↑の作業項目の左の方に「事前チェック」の項目を追加する事は妥当でしょうか？

**Comment by yuuhayashi** [comment]
作業開始の宣言として「タスク予約」をして、
「編集完了」のときにインポート時の変更セットNoを登録してもらいます。
「事前チェック」の工程も、「タスク予約」〜「編集完了」のフェーズの中で行われる作業のひとつと考えます。

”明らかに間違いの建物の有無（地元知識や航空写真でのチェック）や、既存の道路データとの整合性のチェック”は、インポートではなく通常のマッピング活動にあたると思います。
Plateauデータの”事前チェック”のことをいうということでしたら、"*.mrg.osm"での[作業自体](https://github.com/yuuhayashi/citygml-osm/wiki/How_to_use#step-2--%E5%A4%89%E6%8F%9B%E3%81%95%E3%82%8C%E3%81%9Fpoi%E3%81%AE%E7%A2%BA%E8%AA%8D)が事前チェックに当たると考えます。
どちらにしてもタスク管理は他のマッパーとの競合を避けることが目的ですので、「タスク予約」（名称が不適切なら「作業開始宣言」としても良いかも知れません）を行うことで競合の抑止効果があると思います。

**Comment by nyampire** [comment]
> ”明らかに間違いの建物の有無（地元知識や航空写真でのチェック）や、既存の道路データとの整合性のチェック”は、インポートではなく通常のマッピング活動

なるほど。
既存の地物の位置調整も含めて、「タスク予約」に含める、というかんじですね。やること自体は変わらない（どこまで明確に区別するか、程度のお話と思っています）ので、 @yuuhayashi さんの提案のとおりで進めてみましょうか。

個人的には、 `「タスク予約」（名称が不適切なら「作業開始宣言」としても良いかも知れません）` のとおり、「作業開始宣言」のほうが適切な気がしています。
